pipeline {
    agent any

    stages {
        stage('Pull code') {
            steps {
                checkout scm
            }
        }
        stage('Download dependency') {
            steps {
                sh 'cd server-side && yarn install'
            }
        }
        stage('Run Unit test') {
            steps {
                sh 'cd server-side && yarn run test'

                publishHTML target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: false,
                        keepAll: true,
                        reportDir: "./server-side/coverage/lcov-report",
                        reportFiles: "index.html",
                        reportName: 'Unit Test Coverage Report'
                    ]

                    publishHTML target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: false,
                        keepAll: true,
                        reportDir: "./server-side/coverage",
                        reportFiles: "report.html",
                        reportName: 'Unit Test Report'
                    ]
            }
        }
        stage('Run Component test') {
            steps {
                sh 'cd server-side && yarn run test:cov'
            }
        }
        stage('Create Coverage Test Report'){
            steps {
                clover(cloverReportDir: 'server-side/coverage', cloverReportFileName: 'clover.xml',
                    healthyTarget: [methodCoverage: 70, conditionalCoverage: 80, statementCoverage: 80],
                    unhealthyTarget: [methodCoverage: 40, conditionalCoverage: 50, statementCoverage: 50],
                    failingTarget: [methodCoverage: 0, conditionalCoverage: 0, statementCoverage: 0]
                )
            }
        }
        stage('Mongoose test') {
            steps {
                echo 'test mongoose !'
            }
        }
        stage('Build') {
            steps {
                sh 'cd server-side && yarn build'
            }
        }
        stage('Deployment') {
            steps {
                echo 'Deploy server-side'
            }
        }
        stage('Run E2E test') {
            steps {
                // sh 'cd server-side && yarn run test:e2e'
                echo 'E2E command test'
            }
        }
    }
}
