pipeline {
    agent any

    stages {
        stage('Pull code') {
            steps {
                checkout scm
                // git branch: 'main', url: 'https://github.com/peetnawapol/project-01-software-dev-tool'
            }
        }
        stage('Download dependency') {
            steps {
                sh 'cd server-side && yarn install'
            }
        }
        stage('Run Unit test') {
            steps {
                sh 'cd server-side && yarn run test'
            }
        }
        stage('Run Component test') {
            steps {
                sh 'cd server-side && yarn run test:cov'
            }
        }
        stage('Mongoose test') {
            steps {
                echo 'test mongoose'
            }
        }
        stage('Build') {
            steps {
                sh 'cd server-side && yarn build'
            }
        }
        stage('Deployment') {
            steps {
                echo 'Deploy'
            }
        }
        stage('Run E2E test') {
            steps {
                // sh 'cd server-side && yarn run test:e2e'
                echo 'E2E test'
            }
        }
    }
}
