pipeline {
    agent any

    stages {
        stage('Pull code') {
            steps {
                git branch: 'main', url: 'https://github.com/peetnawapol/project-01-software-dev-tool'
            }
        }
        stage('Download dependency') {
            steps {
                sh 'cd client-side && yarn install'
            }
        }
        stage('Run Unit test') {
            steps {
                // sh 'cd client-side && yarn run test'
                echo 'run unit test'
            }
        }
        stage('Run Component test') {
            steps {
                echo 'run component test'
            }
        }
        stage('Graphql test') {
            steps {
                echo 'test graphql api'
            }
        }
        stage('Build') {
            steps {
                sh 'cd client-side && yarn build'
            }
        }
        stage('Deployment') {
            steps {
                echo 'Deploy command'
            }
        }
        stage('Run E2E test') {
            steps {
                echo 'E2E command'
            }
        }
    }
}